### ISSUE TITLE
Determine Features to Disable

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#28]
## Description

There are certain features (e.g. trampolines/retpolines used as a spectre mitigation) that are not relevant for Cairo as a target. We will need to work out how to handle these as some of them use functions generated as part of the Compiler RT.

We want to disable features that get us the highest ratio of saved implementation effort to increased complexity of compilation. Some, like the aforementioned trampolines, are a no-brainer to disable, but others may require a cost-benefit analysis.

**Comment by iamrecursion** [comment]
I think your conclusion is mostly sound but incomplete. 

You are correct that most immediately we are concerned with the Rust to LLVM IR compilation phase, so it is great to know that we don't have to do anything special there.

Looking foward, however, we are also interested in potentially running various LLVM IR opts within our own pipeline. Some of those may be detrimental to our ability to efficiently compile to `FlatLowered`, so part of this task is also to work out which of the non-target specific [passes](https://llvm.org/docs/Passes.html)—the ones you mention above—are relevant, helpful, and detrimental to our work here. 

Sorry for that not being clear before!
