### ISSUE TITLE
Implement Polyfill Scaffolding

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#31]
## Description

In #25 we designed a system to enable polyfilling operations that do not exist on the target architecture. This task deals with the implementation of that system. 

As part of this task it should be integrated with the pre-existing scaffolding for emitting calls to the polyfills as they are implemented.

**Comment by iamrecursion** [comment]
This has transformed to essentially involve implementing linkage. See #25 for the details on what will likely be the case.
