### ISSUE TITLE
Implement a Memory Assignment Pass (Initial)

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#36]
## Description

Once we have decided on an initial memory model (#29) we need to take LLVM’s assumptions about memory and transform them to fit our decided-upon model.

This will have to deal with the somewhat crude controls of memory available to us in `FlatLowered`.

**Comment by iamrecursion** [comment]
Memory is handled explicitly in LLVM, and we have `alloca`, `load`, `store`, `getelementptr` polyfills to be implemented.
