### ISSUE TITLE
Implement Bit Operations (Initial)

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#38]
## Description

In order to have things plumbed into the ALU, we also need the operations on sequences of bits to be implemented. It needs to provide the following:

- swap
- `&`
- `|`
- `~`
- `^` 
- `>>`
- `<<`
- `>>>`
- `ror`
- `rol`
- Count leading zeros
- Index of least-significant 1-bit
- Parity check
- Count 1 bits
- Test

**Comment by iamrecursion** [comment]
This looks good to me!

**Comment by iamrecursion** [comment]
The above makes sense, but I just want to be clear that we will have to do specific type conversions to get the wrapping behavior we need the specific underlying unsigned integer type.

It may _also_ not make sense to use U256 here. It may be implemented as two felts, which is overhead we do not need when the biggest integers we care about for now are u128, so we can safely convert to and from _that_ as a generic representation.
