### ISSUE TITLE
Implement Stack Semantics (Initial)

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#42]
## Description

Given that we have designed the stack semantics (#26), we need to implement them. This task deals with the implementation of the bare minimum of those semantics to make things work correctly. We plan on relying on the existing Cairo VM stack and stack pointer as much as possible until we get to #59.

**Comment by iamrecursion** [comment]
The initial stack semantics are relying directly on the CairoVM stack, and we compile directly to operations that use these. No extra implementation is needed.
