### ISSUE TITLE
Implement Pointer Ops

### ISSUE THREAD

**Issue by ktemkin** [reilabs/hieratika#44]
## Description

We have designed the memory model (#29), but unfortunately it is not sufficient just to have R/W memory semantics. As part of that work we also had to design how pointers would behave, as pointer operations (arithmetic, chasing, and so on) are very important to LLVM-compiled code.

This task deals with implementing the pointer operations properly.

**Comment by iamrecursion** [comment]
Obviated by the memory model design. These are handled within polyfills where necessary as they do not exist as explicit operations in LLVM.
