### ISSUE TITLE
Implement LLVM-IR test harness

### ISSUE THREAD

**Issue by Eagle941** [reilabs/hieratika#99]
# Description
We need to create a crate to test LLVM-IR code.

# Spec

- [x] Execute LLVM-IR code with `lli`, extract the return value and the final memory status.
- [ ] Inspect the final value of any memory cell.

**Comment by iamrecursion** [comment]
I want to clarify the memory thing. We do not care that the memory is the same. This is not ever going to be the case.

What we want is the ability to inspect the _final value of any memory cell_ (not done by default), and assert equalities on those.

**Comment by Eagle941** [comment]
There isn't a straightforward solution to extract the value of memory cells from LLVM-IR execution. The temporary workaround is to use `assert` in the code. If needed, more investigations will be done in the future.
